// Leia um número N, some todos os números inteiros entre 1 e N e escreva o resultado obtido.
// var num = 90
// for(a = 1; a <= num;a++){
//     var soma = num + a
//     console.log(num + " + " + a + " = " + soma)
// }
// Leia um número N, some todos os números inteiros entre 1 e N e escreva o resultado obtido.
var num = 90
soma = 0
for(a = 1; a < num;a++){
    soma += a
    console.log(soma)
}
console.log(soma)